CREATE TABLE MEMORIZER.NOTES (
    ID SERIAL PRIMARY KEY,
    NOTE TEXT NOT NULL,
    DISTRIBUTION_NUMBER INTEGER NOT NULL DEFAULT 0,
    COLLECTION_ID INTEGER NOT NULL,
    FOREIGN KEY (COLLECTION_ID) REFERENCES MEMORIZER.COLLECTIONS(ID)
);